### PR TITLE
changed landing page blur

### LINKED ISSUE #24: Change background to landing page
Change the landing page's background to glass effect.
`https://css-tricks.com/frosting-glass-css-filters/`

### PR DESCRIPTION
**Pull request by SoloNoah**
closes #24

it looks like this now. Lemme know if to change it back. I think it looks better.
image

### CODE REVIEW

**Comment by SoloNoah** [comment]
Compare it to the previous one. 

image

**Comment by AvielCo** [comment]
Looks 🔥🔥🔥🔥🔥

**Comment by AvielCo** [comment]
@EmiliaZorin Your thoughts?

**Comment by SoloNoah** [comment]
gimmie like 15 min i will provide a better pic with the navbar for as well for contrast

**Comment by SoloNoah** [comment]
I think that it complements the nav bar.
played a bit with the line spacing and font size for the "feel". maybe the text should be darker. 
image

**Review by AvielCo — APPROVED** [review]

**Pull request merged**
