### PR TITLE
Link navigation buttons to each page

### LINKED ISSUE #23: Link navigation buttons to each page
When done with #20 #21 #22, link the buttons on the navbar to corresponding page.
scan button to #20 
about button to #21 
credits button to #22

### PR DESCRIPTION
**Pull request by EmiliaZorin**
Fixes #23

Signed-off-by: Emilia <emiliazorin@gmail.com>

### CODE REVIEW

**Review by SoloNoah — CHANGES_REQUESTED** [review]
Missing routing from login/registration/profile to wanted sections on home page

**Comment by AvielCo** [comment]
Yes fix this

**Comment by AvielCo** [comment]
Also fix from profile to logout

**Review by AvielCo — APPROVED** [review]

**Review by AvielCo — APPROVED** [review]

**Review by SoloNoah — APPROVED** [review]
approved
yours truly

**Pull request merged**
